salaries                      = IncomeCategory.create(name: "給与所得")
repayment_of_advance_payments = IncomeCategory.create(name: "立替金返済")
bonuses                       = IncomeCategory.create(name: "賞与")
extraordinary_incomes         = IncomeCategory.create(name: "臨時収入")
business_incomes              = IncomeCategory.create(name: "事業所得")
income_others                 = IncomeCategory.create(name: "その他")

eats                          = SpendingCategory.create(name: "食費")
daily_miscellaneous_goods     = SpendingCategory.create(name: "日曜雑貨")
traffics                      = SpendingCategory.create(name: "交通")
communications                = SpendingCategory.create(name: "通信")
lives                         = SpendingCategory.create(name: "生活")
entertainment_expenses        = SpendingCategory.create(name: "交際費/エンタメ")
educations                    = SpendingCategory.create(name: "教育/教養")
medical_bills                 = SpendingCategory.create(name: "医療/保険")
clothes                       = SpendingCategory.create(name: "美容/衣服")
cars                          = SpendingCategory.create(name: "車")
taxes                         = SpendingCategory.create(name: "税金")
large_expenses                = SpendingCategory.create(name: "大型出費")
others                        = SpendingCategory.create(name: "その他")

eats_1  = eats.children.create(name: "食料品")
eats_2  = eats.children.create(name: "カフェ")
eats_3  = eats.children.create(name: "朝ごはん")
eats_4  = eats.children.create(name: "昼ごはん")
eats_5  = eats.children.create(name: "夜ごはん")
eats_6  = eats.children.create(name: "飲み会")
eats_7  = eats.children.create(name: "その他")

daily_miscellaneous_goods_1  = daily_miscellaneous_goods.children.create(name: "消耗品")
daily_miscellaneous_goods_2  = daily_miscellaneous_goods.children.create(name: "子ども関連")
daily_miscellaneous_goods_3  = daily_miscellaneous_goods.children.create(name: "ペット関連")
daily_miscellaneous_goods_4  = daily_miscellaneous_goods.children.create(name: "タバコ")
daily_miscellaneous_goods_5  = daily_miscellaneous_goods.children.create(name: "その他")

traffics_1  = traffics.children.create(name: "電車")
traffics_2  = traffics.children.create(name: "タクシー")
traffics_3  = traffics.children.create(name: "バス")
traffics_4  = traffics.children.create(name: "飛行機")
traffics_5  = traffics.children.create(name: "その他")

communications_1  = communications.children.create(name: "携帯電話料金")
communications_2  = communications.children.create(name: "固定電話料金")
communications_3  = communications.children.create(name: "インターネット関連費")
communications_4  = communications.children.create(name: "放送サービス料金")
communications_5  = communications.children.create(name: "宅配便")
communications_6  = communications.children.create(name: "切手・はがき")
communications_7  = communications.children.create(name: "その他")

lives_1  = lives.children.create(name: "水道料金")
lives_2  = lives.children.create(name: "電気料金")
lives_3  = lives.children.create(name: "ガス料金")
lives_4  = lives.children.create(name: "家賃")
lives_5  = lives.children.create(name: "住宅ローン")
lives_6  = lives.children.create(name: "家具")
lives_7  = lives.children.create(name: "家電")
lives_8  = lives.children.create(name: "リフォーム")
lives_9  = lives.children.create(name: "住宅保険")
lives_10  = lives.children.create(name: "その他")

entertainment_expenses_1  = entertainment_expenses.children.create(name: "飲み会")
entertainment_expenses_2  = entertainment_expenses.children.create(name: "プレゼント")
entertainment_expenses_3  = entertainment_expenses.children.create(name: "ご祝儀・香典")
entertainment_expenses_4  = entertainment_expenses.children.create(name: "レジャー")
entertainment_expenses_5  = entertainment_expenses.children.create(name: "イベント")
entertainment_expenses_6  = entertainment_expenses.children.create(name: "映画・動画")
entertainment_expenses_7  = entertainment_expenses.children.create(name: "音楽")
entertainment_expenses_8  = entertainment_expenses.children.create(name: "漫画")
entertainment_expenses_9  = entertainment_expenses.children.create(name: "書籍")
entertainment_expenses_10  = entertainment_expenses.children.create(name: "ゲーム")
entertainment_expenses_11  = entertainment_expenses.children.create(name: "その他")

educations_1  = educations.children.create(name: "習い事")
educations_2  = educations.children.create(name: "新聞")
educations_3  = educations.children.create(name: "参考書")
educations_4  = educations.children.create(name: "受験料")
educations_5  = educations.children.create(name: "学費")
educations_6  = educations.children.create(name: "学資保険")
educations_7  = educations.children.create(name: "塾")
educations_8  = educations.children.create(name: "その他")

medical_bills_1  = medical_bills.children.create(name: "病院代")
medical_bills_2  = medical_bills.children.create(name: "薬代")
medical_bills_3  = medical_bills.children.create(name: "生命保険")
medical_bills_4  = medical_bills.children.create(name: "医療保険")
medical_bills_5  = medical_bills.children.create(name: "その他")

clothes_1  = clothes.children.create(name: "洋服")
clothes_2  = clothes.children.create(name: "アクセサリー・小物")
clothes_3  = clothes.children.create(name: "下着")
clothes_4  = clothes.children.create(name: "ジム・健康")
clothes_5  = clothes.children.create(name: "美容院")
clothes_6  = clothes.children.create(name: "コスメ")
clothes_7  = clothes.children.create(name: "エステ・ネイル")
clothes_8  = clothes.children.create(name: "クリーニング")
clothes_9  = clothes.children.create(name: "その他")

cars_1  = cars.children.create(name: "ガソリン")
cars_2  = cars.children.create(name: "駐車場")
cars_3  = cars.children.create(name: "自動車保険")
cars_4  = cars.children.create(name: "自動車税")
cars_5  = cars.children.create(name: "自動車ローン")
cars_6  = cars.children.create(name: "免許教習")
cars_7  = cars.children.create(name: "高速料金")
cars_8  = cars.children.create(name: "その他")

taxes_1  = taxes.children.create(name: "年金")
taxes_2  = taxes.children.create(name: "所得税")
taxes_3  = taxes.children.create(name: "消費税")
taxes_4  = taxes.children.create(name: "住民税")
taxes_5  = taxes.children.create(name: "個人事業税")
taxes_6  = taxes.children.create(name: "その他")

large_expenses_1  = large_expenses.children.create(name: "旅行")
large_expenses_2  = large_expenses.children.create(name: "住宅")
large_expenses_3  = large_expenses.children.create(name: "自動車")
large_expenses_4  = large_expenses.children.create(name: "バイク")
large_expenses_5  = large_expenses.children.create(name: "結婚")
large_expenses_6  = large_expenses.children.create(name: "出産")
large_expenses_7  = large_expenses.children.create(name: "介護")
large_expenses_8  = large_expenses.children.create(name: "家具")
large_expenses_9  = large_expenses.children.create(name: "家電")
large_expenses_10  = large_expenses.children.create(name: "その他")

others_1  = others.children.create(name: "仕送り")
others_2  = others.children.create(name: "お小遣い")
others_3  = others.children.create(name: "使途不明金")
others_4  = others.children.create(name: "立替金")
others_5  = others.children.create(name: "未分類")
others_6  = others.children.create(name: "現金の引出し")
others_7  = others.children.create(name: "カードの引き落とし")
others_8  = others.children.create(name: "電子マネーにチャージ")
others_9  = others.children.create(name: "借金返済")
others_10  = others.children.create(name: "その他")
