IncomeCategory.create(name: "給与所得")
IncomeCategory.create(name: "立替金返済")
IncomeCategory.create(name: "賞与")
IncomeCategory.create(name: "臨時収入")
IncomeCategory.create(name: "事業所得")
IncomeCategory.create(name: "その他")

SpendingCategory.create(name: "食費")
SpendingCategory.create(name: "日曜雑貨")
SpendingCategory.create(name: "交通費")
SpendingCategory.create(name: "通信費")
SpendingCategory.create(name: "生活関連")
SpendingCategory.create(name: "交際費/エンタメ")
SpendingCategory.create(name: "教育/教養")
SpendingCategory.create(name: "医療/保険")
SpendingCategory.create(name: "美容/衣服")
SpendingCategory.create(name: "車関連")
SpendingCategory.create(name: "税金")
SpendingCategory.create(name: "大型出費")
SpendingCategory.create(name: "その他")

Spending.create(item_name: "その他", price: "2021", date: '2017-07-19', memo: "テスト", user_id: "1", spending_category_id: "1")
Spending.create(item_name: "病院代", price: "6000", date: '2021-08-28', memo: "バセドウ病", user_id: "1", spending_category_id: "8")
Spending.create(item_name: "家賃", price: "45328", date: '2020-11-27', memo: "口座から引き落とし", user_id: "1", spending_category_id: "5")
Spending.create(item_name: "まつや", price: "500", date: '2021-12-04', memo: "昼食代", user_id: "1", spending_category_id: "1")
Spending.create(item_name: "新幹線代", price: "42360", date: '2021-11-16', user_id: "1", spending_category_id: "3")
Spending.create(item_name: "コーヒー代", price: "130", date: '2020-01-01', memo: "自販機", user_id: "1", spending_category_id: "1")
Spending.create(item_name: "スーツ用靴", price: "3280", date: '2021-09-30', user_id: "1", spending_category_id: "9")
Spending.create(item_name: "飲み会", price: "3500", date: '2019-01-22', memo: "新年会", user_id: "1", spending_category_id: "6")
Spending.create(item_name: "お菓子", price: "1080", date: '2021-10-04', memo: "差し入れ", user_id: "1", spending_category_id: "6")
Spending.create(item_name: "資格試験代", price: "5766", date: '2021-11-03', user_id: "1", spending_category_id: "7")
Spending.create(item_name: "パチンコ", price: "2000", date: '2017-07-19', memo: "テスト", user_id: "1", spending_category_id: "13")

Income.create(price: "240000", date: '2021-11-11', user_id: "1", income_category_id: "1")
Income.create(price: "3200", date: '2021-11-13', memo: "臨時収入", user_id: "1", income_category_id: "4")

# SpendingCategory.create([{name: "食費_食料品"}, {name: "食費_朝ごはん"}, {name: "食費_昼ごはん"}, {name: "食費_夜ごはん"}, {name: "食費_カフェ"}, {name: "食費_飲み会"}, {name: "食費_その他"}])
# SpendingCategory.create([{name: "日曜雑貨_消耗品"}, {name: "日曜雑貨_子ども関連"}, {name: "日曜雑貨_ペット関連"}, {name: "日曜雑貨_タバコ"}, {name: "日曜雑貨_その他"}])
# SpendingCategory.create([{name: "交通_電車"}, {name: "交通_タクシー"}, {name: "交通_バス"}, {name: "交通_飛行機"}, {name: "交通_その他"}])
# SpendingCategory.create([{name: "通信_携帯電話"}, {name: "通信_固定電話"}, {name: "通信_インターネット関連"}, {name: "通信_放送サービス料金"}, {name: "通信_宅配便"}, {name: "通信_切手・はがき"}, {name: "通信_その他"}])
# SpendingCategory.create([{name: "生活_水道料金"}, {name: "生活_電気料金"}, {name: "生活_ガス料金"}, {name: "生活_家賃"}, {name: "生活_住宅ローン"}, {name: "生活_家具"}, {name: "生活_家電"}, {name: "生活_リフォーム"}, {name: "生活_住宅保険"}, {name: "生活_その他"}])
# SpendingCategory.create([{name: "交際費/エンタメ_プレゼント"}, {name: "交際費/エンタメ_ご祝儀・香典"}, {name: "交際費/エンタメ_レジャー"}, {name: "交際費/エンタメ_イベント"}, {name: "交際費/エンタメ_映画・動画"}, {name: "交際費/エンタメ_音楽"}, {name: "交際費/エンタメ_漫画"}, {name: "交際費/エンタメ_書籍"}, {name: "交際費/エンタメ_ゲーム"}, {name: "交際費/エンタメ_その他"}])
# SpendingCategory.create([{name: "教育/教養_習い事"}, {name: "教育/教養_新聞"}, {name: "教育/教養_参考書"}, {name: "教育/教養_受験料"}, {name: "教育/教養_学費"}, {name: "教育/教養_学資保険"}, {name: "教育/教養_塾"}, {name: "教育/教養_その他"}])
# SpendingCategory.create([{name: "医療/保険_病院代"}, {name: "医療/保険_薬代"}, {name: "医療/保険_生命保険"}, {name: "医療/保険_医療保険"}, {name: "医療/保険_その他"}])
# SpendingCategory.create([{name: "美容/衣服_洋服"}, {name: "美容/衣服_アクセサリー・小物"}, {name: "美容/衣服_下着"}, {name: "美容/衣服_ジム・健康"}, {name: "美容/衣服_美容院"}, {name: "美容/衣服_コスメ"}, {name: "美容/衣服_エステ・ネイル"}, {name: "美容/衣服_クリーニング"}, {name: "美容/衣服_その他"}])
# SpendingCategory.create([{name: "車_ガソリン"}, {name: "車_駐車場"}, {name: "車_自動車保険"}, {name: "車_自動税"}, {name: "車_自動車ローン"}, {name: "車_免許教習"}, {name: "車_高速料金"}, {name: "車_その他"}])
# SpendingCategory.create([{name: "税金_年金"}, {name: "税金_所得税"}, {name: "税金_消費税"}, {name: "税金_住民税"}, {name: "税金_個人事業税"}, {name: "税金_その他"}])
# SpendingCategory.create([{name: "大型出費_旅行"}, {name: "大型出費_住宅"}, {name: "大型出費_自動車"}, {name: "大型出費_バイク"}, {name: "大型出費_結婚"}, {name: "大型出費_出産"}, {name: "大型出費_介護"}, {name: "大型出費_家具"}, {name: "大型出費_家電"}, {name: "大型出費_その他"}])
# SpendingCategory.create([{name: "その他_仕送り"}, {name: "その他_お小遣い"}, {name: "その他_用途不明金"}, {name: "その他_立替金"}, {name: "その他_現金の引出し"}, {name: "その他_カードの引き落とし"}, {name: "その他_電子マネーにチャージ"}, {name: "その他_借金返済"}, {name: "その他_未分類"}, {name: "その他_その他"}])
